version: '3.7'

services:
  database_authentication:
    image: postgres
    container_name: database_authentication
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authenticationnode
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: authenticationnode
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_authentication
    depends_on:
      - database_authentication
    restart: always

volumes:
  pgdata:
    driver: local
